config/routes.rb
Rails.application.routes.draw do

   root 'welcome#index'
     get 'about' =>  'welcome#about'
     get 'plan' =>  'welcome#plan'
     get 'service' =>  'welcome#service'
     get 'career'  =>  'welcome#career'
     get 'contact'  =>  'welcome#contact'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

	def index
		
	end
	def about
		
	end
	def plan
		
	end
	def service
		
	end
	def career
		
	end
	def contact
		
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Gcn</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= yield %>
</div>
<div class="footer"><p>Copyright &copy; 2015 GCN Broadband Pvt. Ltd. - All Rights Reserved.</p></div>
</body>
</html>

app/views/welcome/_navbar.html.erb
<div class="navbar navbar-default">
	<div class="container">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<%= link_to image_tag("logo.png", :border=>0, :class=>'navbar-brand'), root_path, :alt=>"logo" %>
		</div>
		<div class="navbar-collapse collapse navbar-responsive-collapse">
			<ul class="nav navbar-nav navbar-right">
				<li><%= link_to 'Home', root_path %></li>
				<li><%= link_to 'About Us', about_path %></li>
				<li><%= link_to 'Plans', plan_path %></li>
				<li><%= link_to 'Services', service_path %></li>
				<li><%= link_to 'Careers', career_path %></li>
				<li><%= link_to 'Contact Us', contact_path %></li>
			</ul><!--navbar right content -->
		</div>
	</div>
</div>

app/views/welcome/about.html.erb
<div class="wrapper">
	<%= render 'navbar' %>
	<div class="about-banner">
		<%= image_tag "about.jpg", :class=>"img-responsive about-image" %>
		<!-- <h1><b>Hands Together</b></h1> -->
	</div>

	<section>
		<div class="container">
			<div class="row">
				<div class="col-md-12 col-lg-12">
					<div class="page-headings">
						<h1><b>About Us</b></h1>
					    <div class="bottom-line"></div>
					</div>
				</div>
			</div>
		</div>
	</section>

	<section class="about-section-one">
		<div class="container">
			<div class="row">
				<div class="col-md-12 col-lg-12">
					<div class="about-text">
						<p><span>GCN Broadband</span> offers high-speed data, voice and video services through the Internet. Primarily, it offers high speed Internet services to residential, corporate and SME customers. For corporate and SME customers GCN offers dedicated leased line to enable them to send huge amounts of data. Discover our most popular and low-cost way to get a reliable, High speed Internet connection for you, with speeds up to 100 Mbps. We manage traffic on our network to keep things fast and try to make it fair so our business customers get the best performance when they need it most.</p>
					</div>
				</div>
			</div>
		</div>
	</section>
	
	
	<section class="about-section-two">
		<div class="container">
			<div class="row">
				<div class="col-md-6 col-lg-6">
					<div class="about-inner-content">
						<i class="fa fa-eye fa-5x" aria-hidden="true"></i>
						<h2>Vision</h2>
						<p>GCN BROADBAND PVT LTD is aiming at becoming the largest networking service provider in India. Internet is no longer a luxury commodity instead a necessity...</p>
						<div><a href="javascript:void(0)" class="btn btn-sm btn-raised btn-danger">Read More</a></div>
					</div>
				</div>
				<div class="col-md-6 col-lg-6">
					<div class="about-inner-content">
						<i class="fa fa-shield fa-5x" aria-hidden="true"></i>
						<h2>Mission</h2>
						<p>“High speed internet with the lowest cost and almost zero Breakdown” We have a mission to be the best network service provider with prices as low as it can...</p>
						<div><a href="javascript:void(0)" class="btn btn-sm btn-raised btn-danger">Read More</a></div>
					</div>
				</div>
			</div>
			<div class="row">
				<div class="col-md-6 col-lg-6">
					<div class="about-inner-content">
						<i class="fa fa-usd fa-5x" aria-hidden="true"></i>
						<h2>Values</h2>
						<p>Empathy for Customers We offer superior quality of networking services and deal with our competitors fairly. We are genuinely interested in our customers’...</p>
						<div><a href="javascript:void(0)" class="btn btn-sm btn-raised btn-danger">Read More</a></div>
					</div>
				</div>
				<div class="col-md-6 col-lg-6">
					<div class="about-inner-content">
						<i class="fa fa-heart fa-5x" aria-hidden="true"></i>
						<h2>Honesty</h2>
						<p>At GCN BROADBAND PVT LTD we believe that Honesty is the highest form of intimacy, we have maintained honesty and transparency in our ...</p>
						<p><div><a href="javascript:void(0)" class="btn btn-sm btn-raised btn-danger">Read More</a></div></p>
					</div>	
				</div>
			</div>
		</div>
	</section>

	<section>
		<div class="container">
			<div class="row">
				<div class="col-md-12 col-lg-12">
					
				</div>
			</div>
		</div>
	</section>
	

</div>
<div class="bottom-fix"></div>

app/views/welcome/career.html.erb
<div class="wrapper">
	<%= render 'navbar' %>
</div>	

app/views/welcome/contact.html.erb
<div class="wrapper">
	<%= render 'navbar' %>
	<div class="about-banner">
		<%= image_tag "customerservice.jpg", :class=>"img-responsive about-image" %>
		<h4>Get in touch with us</h4>
	</div>

	<section>
		<div class="container">
			<div class="row">
				<div class="col-md-12 col-lg-12">
					<div class="page-headings">
					<h1><b>Contact Us</b></h1>
						<div class="bottom-line"></div>
					</div>
				</div>
			</div>
		</div>
	</section>

	<section>
		<div class="container">
			<div class="row">
				<div class="col-md-12 col-lg-12">
					<div class="contact-area">
						<div class="col-md-4">
							<div class="location-form">
								<div class="form-group">
									<select id="contactlist" class="form-control">
										<option value="a">Apple fritter</option>
										<option value="b">Croissant</option>
										<option value="c">Donut</option>
										<option value="d">Financier</option>
										<option value="e">Jello</option>
										<option value="f">Madeleine</option>
										<option value="g">Pound cake</option>
										<option value="h">Pretzel</option>
										<option value="i">Sfogliatelle</option>
									</select>
									<i class="fa fa-map-marker fa-2x" aria-hidden="true"></i>
								</div>
							</div>
						</div><!--selector -->
						<div class="col-md-8">
							<div class="select-block pane-1"><h1>one</h1></div>
							<div class="select-block pane-2"><h1>two</h1></div>
							<div class="select-block pane-3"><h1>three</h1></div>
							<div class="select-block pane-4"><h1>four</h1></div>
							<div class="select-block pane-5"><h1>five</h1></div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</section>
</div>
<div class="bottom-fix"></div>

app/views/welcome/index.html.erb
<div class="wrapper">

	<%= render 'navbar' %>
	<div class="container">
		<div id="banner_slider">
		  <div class="slide-1">
		    <div class="blur"></div>
		  </div>
		  <div class="slide-2">
		    <div class="blur"></div>
		  </div>
		  <div class="slide-3">
		    <div class="blur"></div>
		  </div>
		  <div class="slide-4">
		    <div class="blur"></div>
		  </div>
		  <div class="slide-5">
		    <div class="blur"></div>
		  </div> 
		</div><!-- <div id="banner_slider"> -->
	</div>

</div>
<div class="home-footer"></div>
<div class="wrapper-two">
	<section class="index-section">
		<div class="container">
			<div class="row">
				<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
					<div class="text-center"><i class="fa fa-globe fa-5x" aria-hidden="true"></i></i></div>
					<h1 class="text-center">Welcome to GCN Broadband</h1>
				</div>
			</div>
			<div class="row">
				<div class="col-xs-12 col-sm-12 col-md-8 col-lg-7">
					<p class="gcn-headlines">GCN Broadband offers high-speed data, voice and video services through the Internet. Primarily, it offers high speed Internet services to residential, corporate and SME customers. For corporate and SME customers GCN offers dedicated leased line to enable them to send huge amounts of data. Discover our most popular and low-cost way to get a reliable, High speed Internet connection for you, with speeds up to 100 Mbps. We manage traffic on our network to keep things fast and try to make it fair so our business customers get the best performance when they need it most.</p>
				</div>
				<div class="col-xs-12 col-sm-12 col-md-4 col-lg-5">
					<%= image_tag "highspeed1.png", :class=>"img-responsive high-speed" %>
				</div>
			</div>
		</div>
	</section>
</div>

app/views/welcome/plan.html.erb
<div class="wrapper">
	<%= render 'navbar' %>
</div>	

app/views/welcome/service.html.erb
<div class="wrapper">
	<%= render 'navbar' %>
</div>	